// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCTC754k2sjPmToBQ16K7fENRPWLpCpvw',
    appId: '1:303703149415:web:590272b3b5b70e73097dc2',
    messagingSenderId: '303703149415',
    projectId: 'cine-vault-movil',
    authDomain: 'cine-vault-movil.firebaseapp.com',
    storageBucket: 'cine-vault-movil.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcXGdbAvRkOpEhRQZHz0_rzWoE-_dYEwI',
    appId: '1:303703149415:android:7c440d8c98df1f00097dc2',
    messagingSenderId: '303703149415',
    projectId: 'cine-vault-movil',
    storageBucket: 'cine-vault-movil.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZQJOea-h21bQVofY_RCRoH0j8tOPqR6w',
    appId: '1:303703149415:ios:6da938495db8506a097dc2',
    messagingSenderId: '303703149415',
    projectId: 'cine-vault-movil',
    storageBucket: 'cine-vault-movil.firebasestorage.app',
    iosBundleId: 'com.example.cineVault',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZQJOea-h21bQVofY_RCRoH0j8tOPqR6w',
    appId: '1:303703149415:ios:6da938495db8506a097dc2',
    messagingSenderId: '303703149415',
    projectId: 'cine-vault-movil',
    storageBucket: 'cine-vault-movil.firebasestorage.app',
    iosBundleId: 'com.example.cineVault',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCTC754k2sjPmToBQ16K7fENRPWLpCpvw',
    appId: '1:303703149415:web:02c6f271975cb672097dc2',
    messagingSenderId: '303703149415',
    projectId: 'cine-vault-movil',
    authDomain: 'cine-vault-movil.firebaseapp.com',
    storageBucket: 'cine-vault-movil.firebasestorage.app',
  );

}